---
all:
  children:
    admin_client:
      hosts:
        192.168.84.1: {}
    android_emulator:
      hosts:
        192.168.71.42: {}
        192.168.71.43: {}
    ansible:
      hosts:
        192.168.80.1: {}
    cassandra:
      hosts:
        192.168.83.1: {}
        192.168.83.2: {}
        192.168.83.3: {}
        192.168.83.4: {}
    cluster:
      hosts: {}
    collection_client:
      hosts:
        192.168.81.5: {}
    collector_topology:
      hosts:
        192.168.82.1: {}
    common:
      hosts: {}
    configuration_service:
      hosts:
        192.168.80.2: {}
    discovery_service:
      hosts:
        192.168.80.2: {}
    emulator_collector_server:
      hosts:
        192.168.71.108: {}
    emulator_collector_worker:
      hosts:
        192.168.71.107: {}
    expansion_client:
      hosts:
        192.168.81.3: {}
    flow_manager:
      hosts:
        192.168.82.1: {}
    jback:
      hosts:
        192.168.84.1: {}
    jclient:
      hosts:
        192.168.84.1: {}
    jdown:
      hosts:
        192.168.82.1: {}
    jenkins:
      hosts:
        192.168.80.1: {}
    jet_service:
      hosts:
        192.168.71.109: {}
        192.168.71.110: {}
    jfile:
      hosts:
        192.168.81.1: {}
    jgate:
      hosts:
        192.168.82.1: {}
    jhtop:
      hosts:
        192.168.81.1: {}
    jlimiter:
      hosts:
        192.168.82.1: {}
    jscheduler:
      hosts:
        192.168.81.2: {}
    jtool:
      hosts:
        192.168.83.1: {}
    mariadb:
      hosts:
        192.168.83.4: {}
    mnw2vec:
      hosts:
        192.168.81.4: {}
    mongodb:
      hosts:
        192.168.83.1: {}
        192.168.83.2: {}
        192.168.83.3: {}
    msearch_solr:
      hosts:
        192.168.81.4: {}
    mstory:
      hosts:
        192.168.81.4: {}
    payment_service:
      hosts:
        192.168.81.2: {}
    policy_management:
      hosts:
        192.168.81.2: {}
    postgres:
      hosts:
        192.168.83.4: {}
    puppet_master:
      hosts:
        192.168.81.3: {}
    puppet_worker:
      hosts:
        192.168.82.3: {}
    query_director:
      hosts:
        192.168.81.2: {}
    query_manager:
      hosts:
        192.168.81.2: {}
    queue_dispatcher:
      hosts:
        192.168.82.1: {}
    rabbitmq:
      hosts:
        192.168.82.1: {}
    redis:
      hosts:
        192.168.83.4: {}
    report_service:
      hosts:
        192.168.81.3: {}
    secure:
      hosts: {}
    sensu_master:
      hosts:
        192.168.80.1: {}
    social_data_service:
      hosts:
        192.168.81.5: {}
    solr:
      hosts:
        192.168.83.10: {}
        192.168.83.11: {}
        192.168.83.8: {}
        192.168.83.9: {}
    squid:
      hosts:
        192.168.80.1: {}
    storm_nimbus:
      hosts:
        192.168.82.1: {}
    storm_supervisor:
      hosts:
        192.168.82.2: {}
    telegram_service:
      hosts:
        192.168.82.3: {}
    topic_collector:
      hosts:
        192.168.81.3: {}
    topic_service:
      hosts:
        192.168.81.3: {}
    unity_service:
      hosts:
        192.168.71.106: {}
    users_management:
      hosts:
        192.168.81.2: {}
    voyager_servers:
      hosts:
        192.168.71.106: {}
        192.168.71.107: {}
        192.168.71.108: {}
        192.168.71.109: {}
        192.168.71.110: {}
        192.168.71.42: {}
        192.168.71.43: {}
        192.168.80.1: {}
        192.168.80.2: {}
        192.168.81.1: {}
        192.168.81.2: {}
        192.168.81.3: {}
        192.168.81.4: {}
        192.168.81.5: {}
        192.168.82.1: {}
        192.168.82.2: {}
        192.168.82.3: {}
        192.168.83.1: {}
        192.168.83.10: {}
        192.168.83.11: {}
        192.168.83.2: {}
        192.168.83.3: {}
        192.168.83.4: {}
        192.168.83.5: {}
        192.168.83.6: {}
        192.168.83.7: {}
        192.168.83.8: {}
        192.168.83.9: {}
        192.168.84.1: {}
      vars:
        alias: va-czr
        env: onprem
        platform: vmware
        project: va
    zookeeper:
      hosts:
        192.168.83.5: {}
        192.168.83.6: {}
        192.168.83.7: {}
  hosts:
    192.168.71.106:
      '#': '23'
      Name: va-czr-unity
      components: unity-service
      ip address: 192.168.71.106
      memory gb: '4'
      name: va-czr-unity
      private_ip: 192.168.71.106
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '2'
    192.168.71.107:
      '#': '26'
      Name: va-czr-emulator-worker
      components: emulator-collector-worker
      ip address: 192.168.71.107
      memory gb: '2'
      name: va-czr-emulator-worker
      private_ip: 192.168.71.107
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '2'
    192.168.71.108:
      '#': '27'
      Name: va-czr-emulator-server
      components: emulator-collector-server
      ip address: 192.168.71.108
      memory gb: '4'
      name: va-czr-emulator-server
      private_ip: 192.168.71.108
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '2'
    192.168.71.109:
      '#': '24'
      Name: va-czr-jet-1
      components: jet-service
      ip address: 192.168.71.109
      memory gb: '16'
      name: va-czr-jet-1
      private_ip: 192.168.71.109
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
    192.168.71.110:
      '#': '25'
      Name: va-czr-jet-2
      components: jet-service
      ip address: 192.168.71.110
      memory gb: '16'
      name: va-czr-jet-2
      private_ip: 192.168.71.110
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
    192.168.71.42:
      '#': '28'
      Name: va-czr-android-1
      components: android-emulator
      ip address: 192.168.71.42
      name: va-czr-android-1
      private_ip: 192.168.71.42
      tier: collection
    192.168.71.43:
      '#': '29'
      Name: va-czr-android-2
      components: android-emulator
      ip address: 192.168.71.43
      name: va-czr-android-2
      private_ip: 192.168.71.43
      tier: collection
    192.168.80.1:
      '#': '1'
      Name: va-czr-adm-1
      components: jenkins, ansible, sensu-master, squid
      ip address: 192.168.80.1
      memory gb: '8'
      name: va-czr-adm-1
      private_ip: 192.168.80.1
      storage gb: 100gb hdd for root partition
      tier: admin
      vcpu: '4'
    192.168.80.2:
      '#': '2'
      Name: va-czr-adm-2
      components: configuration-service, discovery-service
      ip address: 192.168.80.2
      memory gb: '4'
      name: va-czr-adm-2
      private_ip: 192.168.80.2
      storage gb: 100gb hdd for root partition
      tier: admin
      vcpu: '2'
    192.168.81.1:
      '#': '3'
      Name: va-czr-app-1
      components: jfile, jhtop
      ip address: 192.168.81.1
      memory gb: '16'
      name: va-czr-app-1
      private_ip: 192.168.81.1
      storage gb: 100gb hdd for root partition+2nd 500gb hdd attached
      tier: app
      vcpu: '4'
    192.168.81.2:
      '#': '4'
      Name: va-czr-app-2
      components: jscheduler, payment-service, query-manager, query-director, users-management,
        policy-management
      ip address: 192.168.81.2
      memory gb: '8'
      name: va-czr-app-2
      private_ip: 192.168.81.2
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '2'
    192.168.81.3:
      '#': '5'
      Name: va-czr-app-3
      components: expansion-client, topic-collector, topic-service, report-service,
        puppet-master
      ip address: 192.168.81.3
      memory gb: '8'
      name: va-czr-app-3
      private_ip: 192.168.81.3
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
    192.168.81.4:
      '#': '6'
      Name: va-czr-app-4
      components: mnw2vec, mstory, msearch-solr
      ip address: 192.168.81.4
      memory gb: '16'
      name: va-czr-app-4
      private_ip: 192.168.81.4
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '8'
    192.168.81.5:
      '#': '7'
      Name: va-czr-app-5
      components: collection-client, social-data-service
      ip address: 192.168.81.5
      memory gb: '8'
      name: va-czr-app-5
      private_ip: 192.168.81.5
      storage gb: 100gb hdd for root partition
      tier: app
      vcpu: '4'
    192.168.82.1:
      '#': '8'
      Name: va-czr-col-1
      components: storm-nimbus, collector-topology, flow-manager, jdown, jgate, jlimiter,
        queue-dispatcher, rabbitmq
      ip address: 192.168.82.1
      memory gb: '16'
      name: va-czr-col-1
      network: public static ip
      private_ip: 192.168.82.1
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    192.168.82.2:
      '#': '9'
      Name: va-czr-col-2
      components: storm-supervisor
      ip address: 192.168.82.2
      memory gb: '16'
      name: va-czr-col-2
      network: public static ip
      private_ip: 192.168.82.2
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    192.168.82.3:
      '#': '10'
      Name: va-czr-col-3
      components: telegram-service, puppet-worker
      ip address: 192.168.82.3
      memory gb: '8'
      name: va-czr-col-3
      network: public static ip
      private_ip: 192.168.82.3
      storage gb: 100gb hdd for root partition
      tier: collection
      vcpu: '4'
    192.168.83.1:
      '#': '11'
      Name: va-czr-db-1
      components: cassandra, jtool, mongodb
      ip address: 192.168.83.1
      memory gb: '8'
      name: va-czr-db-1
      private_ip: 192.168.83.1
      storage gb: 100gb hdd for root partition+ 2nd 200gb hdd for dbpartition (mounted
        on /opt/cassandra)+ 3rd 200gb hddpartition (mounted on /opt/cassandra/dump)
      tier: db
      vcpu: '4'
    192.168.83.10:
      '#': '20'
      Name: va-czr-db-10
      components: solr
      ip address: 192.168.83.10
      memory gb: '16'
      name: va-czr-db-10
      private_ip: 192.168.83.10
      storage gb: 100gb hdd for root partition+2nd 200gb hdd for dbpartition (mounted
        on /opt/solr)
      tier: db
      vcpu: '4'
    192.168.83.11:
      '#': '21'
      Name: va-czr-db-11
      components: solr
      ip address: 192.168.83.11
      memory gb: '16'
      name: va-czr-db-11
      private_ip: 192.168.83.11
      storage gb: 100gb hdd for root partition+2nd 200gb hdd for dbpartition (mounted
        on /opt/solr)
      tier: db
      vcpu: '4'
    192.168.83.2:
      '#': '12'
      Name: va-czr-db-2
      components: cassandra, mongodb
      ip address: 192.168.83.2
      memory gb: '8'
      name: va-czr-db-2
      private_ip: 192.168.83.2
      storage gb: 100gb hdd for root partition+ 2nd 200gb hdd for dbpartition (mounted
        on /opt/cassandra)+ 3rd 200gb hddpartition (mounted on /opt/cassandra/dump)
      tier: db
      vcpu: '4'
    192.168.83.3:
      '#': '13'
      Name: va-czr-db-3
      components: cassandra, mongodb
      ip address: 192.168.83.3
      memory gb: '8'
      name: va-czr-db-3
      private_ip: 192.168.83.3
      storage gb: 100gb hdd for root partition+ 2nd 200gb hdd for dbpartition (mounted
        on /opt/cassandra)+ 3rd 200gb hddpartition (mounted on /opt/cassandra/dump)
      tier: db
      vcpu: '4'
    192.168.83.4:
      '#': '14'
      Name: va-czr-db-4
      components: cassandra, mariadb, redis, postgres
      ip address: 192.168.83.4
      memory gb: '8'
      name: va-czr-db-4
      private_ip: 192.168.83.4
      storage gb: 100gb hdd for root partition+ 2nd 200gb hdd for dbpartition (mounted
        on /opt/cassandra)+ 3rd 200gb hddpartition (mounted on /opt/cassandra/dump)
      tier: db
      vcpu: '4'
    192.168.83.5:
      '#': '15'
      Name: va-czr-db-5
      components: zookeeper
      ip address: 192.168.83.5
      memory gb: '4'
      name: va-czr-db-5
      private_ip: 192.168.83.5
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    192.168.83.6:
      '#': '16'
      Name: va-czr-db-6
      components: zookeeper
      ip address: 192.168.83.6
      memory gb: '4'
      name: va-czr-db-6
      private_ip: 192.168.83.6
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    192.168.83.7:
      '#': '17'
      Name: va-czr-db-7
      components: zookeeper
      ip address: 192.168.83.7
      memory gb: '4'
      name: va-czr-db-7
      private_ip: 192.168.83.7
      storage gb: 100gb hdd for root partition
      tier: db
      vcpu: '2'
    192.168.83.8:
      '#': '18'
      Name: va-czr-db-8
      components: solr
      disks:
        - device: /dev/sdb
          label: solr
      extra_disks: '[{''device'':''/dev/sdb'',''label'':''solr''}]'
      ip address: 192.168.83.8
      memory gb: '16'
      name: va-czr-db-8
      private_ip: 192.168.83.8
      storage gb: 100gb hdd for root partition+2nd 200gb hdd for dbpartition (mounted
        on /opt/solr)
      tier: db
      vcpu: '4'
    192.168.83.9:
      '#': '19'
      Name: va-czr-db-9
      components: solr
      ip address: 192.168.83.9
      memory gb: '16'
      name: va-czr-db-9
      private_ip: 192.168.83.9
      storage gb: 100gb hdd for root partition+2nd 200gb hdd for dbpartition (mounted
        on /opt/solr)
      tier: db
      vcpu: '4'
    192.168.84.1:
      '#': '22'
      Name: va-czr-web-1
      components: jback, jclient, admin-client
      ip address: 192.168.84.1
      memory gb: '8'
      name: va-czr-web-1
      network: public static ip
      private_ip: 192.168.84.1
      storage gb: 100gb hdd for root partition
      tier: web
      vcpu: '4'
